config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'restaurants' => 'restaurants#index'
  resources :restaurants do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  has_many :reviews, dependent: :destroy

  validates :name, length: { minimum: 3 }, uniqueness: true

end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, inclusion: (1..5) 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
      if @restaurant.save
        redirect_to restaurants_path
      else
        render 'new'
      end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = "Restaurant deleted succesfully"
    redirect_to '/restaurants'
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :description)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @restaurant.reviews.create(review_params)
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
     # You need to implement the method below in your model (e.g. app/models/user.rb)
     @user = User.from_omniauth(request.env["omniauth.auth"])

     if @user.persisted?
       sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
       set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
     else
       session["devise.facebook_data"] = request.env["omniauth.auth"]
       redirect_to new_user_registration_url
     end
   end

   def failure
     redirect_to root_path
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title YelpClone
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = alert
    = notice
  - if user_signed_in?
    = link_to "Sign out", destroy_user_session_path, method: :delete
  - else
    = link_to "Sign in", new_user_session_path
    = link_to "Sign up", new_user_registration_path
    = link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path
    = yield

app/views/restaurants/edit.html.haml
= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.label :description
  = f.text_area :description
  = f.submit

app/views/restaurants/index.html.haml
- if @restaurants.any?
  - @restaurants.each do |restaurant|
    = link_to restaurant.name, restaurant_path(restaurant)
    = link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
    = link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete
    = link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant)
    -# = link_to restaurant.reviews, restaurant_review_path(restaurant)
- else
  %h1 No restaurants yet!

%a(href='/restaurants/new') Add a restaurant

app/views/restaurants/new.html.haml
= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.submit

  - if @restaurant.errors.any?
    %section#errors
      %h2
        = pluralize @restaurant.errors.count, 'error'
        prohibited this restaurant from being saved:
      %ul
        - @restaurant.errors.full_messages.each do |message|
          %li= message

app/views/restaurants/show.html.haml
%p= @restaurant.name
%p= @restaurant.description
- @restaurant.reviews.each do |review|
  Thoughts:
  %p= review.thoughts
  Rating:
  %p= review.rating

app/views/reviews/new.html.haml
= form_for [@restaurant, @review] do |f|
  = f.label :thoughts
  = f.text_area :thoughts
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Leave Review'